.travis.yml
opam
src/compiler/defaults.ml

To make the tests pass, I also:
- Added a missing space in the code generation.
- Added a depext on capnp.
- Added core_extended to the test dependencies.
(before before merging this PR, you should enable tests on this repository at https://travis-ci.org/ -> Accounts, otherwise it won't be active until the next change)
Sample output: https://travis-ci.org/talex5/capnp-ocaml/builds/226759579

Run unit-tests with Travis

---

.gitignore
.merlin
.travis.yml
opam
src/compiler/defaults.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/runtime/builder-inc.ml
src/runtime/reader-inc.ml
src/tests/testEncoding.ml

Before, the only ways to create a struct were as a root, or as a child with a type declared in the schema. For AnyPointer types, we need to be able to add any struct to a message.
This commit adds two new auto-generated operations to structs:
- `Child.init_pointer ptr` allocates a fresh `Child` struct, storing a pointer to it in `ptr`, and returns its builder.
- `Child.of_pointer ptr` returns a reader for the `Child` struct pointed to by `ptr`.
Also, it is sometimes necessary to set an AnyPointer to an interface rather than to a struct. For this, there are two new generated operations on pointers: `field_set_interface` and `field_get_interface`.

Add missing support for pointers

---

opam

Otherwise, building fails on OCaml 4.03 and 4.04 with:
See also: #16

Require sexplib < v0.9.0

---

README.adoc
src/compiler/genCommon.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/compiler/generate.ml
src/compiler/pluginSchema.ml
src/compiler/pluginSchema.mli
src/tests/testEncoding.ml

Add `reader_t` and `builder_t` types to the generated files, plus an abstract type for each struct. Each struct reader is then defined as `struct_type reader_t`, and each builder as `struct_type builder_t`. This makes it possible to define generic functions that work on all readers or builders, without having to generate a separate function for each one.
Use this to replace all the `of_pointer` functions with a single `Reader.of_pointer`.
This also makes interface types abstract, in preparation for allowing capabilities to be attached to messages. The types were previously declared as `int option`, but this wasn't exposed or used anywhere.

Add parameterised reader_t and builder_t types

---

src/compiler/defaults.ml
src/compiler/defaults.mli
src/compiler/genModules.ml
src/compiler/generate.ml
src/compiler/pluginSchema.ml
src/compiler/pluginSchema.mli
src/runtime/builderInc.ml
src/runtime/builderOps.ml
src/runtime/commonInc.ml
src/runtime/message.ml
src/runtime/messageSig.ml
src/runtime/readerInc.ml

Before, each generated module defined its own types. This meant that a struct reader from one schema file (e.g. from an AnyPointer) couldn't be used with another.
This was a problem for the RPC system, which would like to give user code a request or response struct of the expected type, but this type is defined in the application's own schema file.
To support this, I have added a phantom type to `StructStorage`, and defined `StructStorage.reader_t` and `StructStorage.builder_t` types using it. The generated schema files expose that their reader and builder types are equal to these.
We don't want to expose the fact that all `StructStorage.t` types are really equal to the compiler, since then it can't detect when the user isn't following the schema. Instread, `StructStorage.t` is now …

Share the definitions of reader_t and builder_t

---

src/benchmark/capnpCarsales.ml
src/benchmark/capnpCatrank.ml
src/benchmark/capnpEval.ml
src/benchmark/jbuild
src/benchmark/main.ml
src/benchmark/methods.ml
src/benchmark/testCaseSig.ml
src/compiler/genCommon.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/compiler/generate.ml
src/compiler/pluginSchema.ml
src/compiler/pluginSchema.mli
src/runtime/message.ml
src/runtime/messageSig.ml
src/tests/jbuild

Instead of declaring a load of unique type names at the start of the file, use polymorphic variants. These don't need to be declared before use.
e.g.
type struct_Foo_11668594054516559475
type reader_t_Foo_11668594054516559475 = struct_Foo_11668594054516559475 reader_t
type builder_t_Foo_11668594054516559475 = struct_Foo_11668594054516559475 builder_t
module Foo : sig
type t = reader_t_Foo_11668594054516559475
type builder_t = builder_t_Foo_11668594054516559475
val of_builder : builder_t -> t
becomes
module Foo : sig
type struct_t = [`Foo_a1ef2c783fb1ce73]
type t = struct_t reader_t
val of_builder : struct_t builder_t -> t
This simplifies imports (all uses of `Obj.magic` have been removed from the generated code).
It also makes it possible to refer to a type before applying the generated …

Use polymorphic variants for phantom types

---

README.adoc
src/compiler/genCommon.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/compiler/generate.ml
src/runtime/capnp.ml
src/runtime/rPC.ml

Readers and builders for the implicit parameters and results structures are now generated.
A new `Client` module contains a sub-module for each interface, with a sub-module for each method. Each method contains `Params` and `Results` sub-module aliases (params to a builder, results to a reader) and the method ID.
A new `Service` module provides a similar structure for service authors, but where `Params` is a reader and `Results` is a builder.

Generate code for methods

---

capnp.opam
src/benchmark/jbuild
src/benchmark/methods.ml
src/compiler/jbuild
src/compiler/main.ml
src/runtime/builderInc.ml
src/runtime/builderOps.ml
src/runtime/bytesStorage.ml
src/runtime/cArray.ml
src/runtime/capnp.ml
src/runtime/codecs.ml
src/runtime/codecs.mli
src/runtime/codecsSig.ml
src/runtime/commonInc.ml
src/runtime/farPointer.ml
src/runtime/fragmentBuffer.ml
src/runtime/jbuild
src/runtime/listPointer.ml
src/runtime/message.ml
src/runtime/otherPointer.ml
src/runtime/packing.ml
src/runtime/readerInc.ml
src/runtime/structPointer.ml
src/runtime/util.ml
src/tests/jbuild
src/unix/iO.ml
src/unix/iO.mli
src/unix/jbuild

This PR removes the dependency on `Core_kernel` from the `capnp` library (runtime).
- The main problem was the `Deque` module. However, we didn't use most of its features, so I wrote a short replacement. It makes me a bit nervous, but the module seems to have good tests.
- There is also a simple reimplementation of `List.init`.
The other uses of `Core_kernel` had direct equivalents in the standard library.
I also moved the `Capnp.IO` module to `Capnp_unix.IO`, as unikernels can't depend on `Unix`.
However, we may need to patch the `uint` library too (or switch to a different one; see #9).
/cc @hannesm

Mirage unikernel support

---

.travis.yml
capnp.opam
src/compiler/main.ml
src/tests/testCodecs.ml

- It appears that `Exn.backtrace` was removed from base in v0.9.114.39. The commit does not say why.
- `List.gen'` has been replaced by `List.gen_with_length`.

Fix API changes in Base and Core_kernel

---

capnp.opam

Also, it is now a test dependency. This allows capnp to be used on platforms without the compiler, but it does mean that packages that compile schema files will need to add their own dependency on the C++ compiler.

Depend on conf-capnproto for capnproto compiler

---

capnp.opam
src/benchmark/dune
src/benchmark/methods.ml

It's a large dependency, which was only being used for benchmarking.

Remove dependency on Core

---

capnp.opam
src/benchmark/dune
src/compiler/defaults.ml
src/compiler/genCommon.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/compiler/generate.ml
src/compiler/main.ml
src/unix/dune
src/unix/iO.ml

Core_kernel is now only needed for the tests. This greatly reduces the number of libraries you need to install to run the schema compiler. This is on top of #55.

Remove core kernel

---

capnp.opam
src/compiler/main.ml
src/runtime/cArray.ml
src/unix/dune
src/unix/iO.ml
src/unix/iO.mli

- Remove `extunix` dependency. `write_message_to_file_robust` was the only user of the `extunix` library and doesn't appear to be used by anything. Writing a file atomically seems like a general function that should be provided by an external library.
- Removing `extunix` also removes the indirect dependency on `camlp4`, which in turn allows `capnp` to build with OCaml 4.08 (and to build faster on all versions).
- Remove `Pervasives` qualifier. Since we no longer open any replacement standard libraries, we can refer to the default ones without a prefix. This is needed to support OCaml 4.08, which otherwise fails with:
Error (alert deprecated): module Stdlib.Pervasives
Use Stdlib instead.

Remove extunix and camlp4 dependencies

---

capnp.opam
src/benchmark/capnpCatrank.ml
src/benchmark/capnpEval.ml
src/benchmark/dune
src/benchmark/main.ml
src/tests/dune
src/tests/testCodecs.ml
src/tests/testEncoding.ml

Turns out that `Base_quickcheck` can do the same things.

Remove test dependency on Core_kernel

---

src/tests/testEncoding.ml

Error (compiling in dev mode) was:
Error (alert deprecated): module Stdlib.Pervasives

Fix compilation on OCaml 4.08

---

capnp.opam
src/compiler/defaults.ml
src/compiler/defaults.mli
src/compiler/genCommon.ml
src/compiler/genModules.ml
src/compiler/genSignatures.ml
src/compiler/generate.ml
src/compiler/pluginSchema.ml
src/compiler/pluginSchema.mli
src/runtime/builderInc.ml
src/runtime/bytesStorage.ml
src/runtime/dune
src/runtime/message.ml
src/runtime/messageSig.ml
src/runtime/messageStorage.ml
src/runtime/otherPointer.ml
src/runtime/rPC.ml
src/runtime/readerInc.ml
src/runtime/util.ml
src/tests/testBytesStorage.ml
src/tests/testEncoding.ml

Uint 2.0.1 is just a wrapper around stdint, so upgrading no longer requires an API change.
Fixes #9.

Upgrade from uint to stdint

---

src/compiler/genCommon.ml
src/tests/dune
src/tests/test-iface-import.capnp
src/tests/testEncoding.ml

Before, we didn't recognise imported structs or interfaces that were referenced from method parameters or results. There was a `FIXME` in the code about this.
The unit-test added by this PR fails with the original code with the error:
File "src/tests/test_iface_import.mli", line 25, characters 27-41:
25 |           val x_get : t -> TestAllTypes.t
^^^^^^^^^^^^^^
Error: Unbound module TestAllTypes
With the change, the generated line is:
val x_get : t -> [`TestAllTypes_a0a8f314b80b63fd] reader_t

Explore interfaces in find_interesting_import_ids

---

capnp.opam

Dune should not be a build dependency

---

capnp.opam
src/tests/testEncoding.ml

Otherwise, it fails on 32-bit systems with:
File "src/tests/testEncoding.ml", line 84, characters 37-47:
84 |   u_int32_field_set s (Uint32.of_int 3456789012);
Error: Integer literal exceeds the range of representable integers of type int

Replace `Uint32.of_int` in unit-tests with of_string

---

src/benchmark/fastRand/fast_rand.c

Very minor fix - `long` is always 32-bits on Windows. Given that the idea is to have an error on a 32-bit system, how about this instead? The other option would be to keep the existing code but use `SIZEOF_PTR` (from `m.h` which is included by `caml/mlvalues.h`)

Remove incorrect test for 64-bit on Windows

---

dune-project
src/benchmark/dune
src/benchmark/fastRand/dune
src/benchmark/test.py
src/tests/dune

Also, update test script to Python 3 and only build benchmark on `x86_64` (it should work on any 64-bit platform, but dune's `enabled_if` won't let you check for that).

Update to dune 2

---

src/runtime/codecs.ml
src/runtime/codecs.mli
src/tests/testCodecs.ml

Currently the fold and iter serializers allow for operations over the fragments which make up a message, however they still involve a copy if the segment isn't full.
This pull request exposes the underlying fragments such that they can be written directly to a socket.
It also adds a basic test for the folding serializer which previously didn't have one.

Add copyless fold and iter

---

CHANGES.md
src/benchmark/test.py
src/runtime/dune
src/unix/dune

This was needed to get flambda to inline the functor, but I don't think anyone is using flambda and it massively slows down the build for everyone else. We can try optimising it again once flambda2 is ready.
On OCaml 4.13 on my machine, this reduced the build time from 16s to 3s (tested with `rm -rf _build && time dune build --release`).

Remove compiler flags for flambda

---

capnp.opam

- Depend on dune >= 2.3
- Don't try to build benchmarks; that only works on some platforms.

Minor opam fixes

---

src/compiler/genModules.ml
src/runtime/rPC.ml

It reported the ID of the actual object, not the ID that was requested.
Also, add pretty-printer for interfaces from the registry.

Fix "Unknown interface" error

---

capnp.opam
src/benchmark/capnpCarsales.ml
src/benchmark/capnpCatrank.ml
src/benchmark/capnpEval.ml
src/benchmark/dune
src/compiler/dune
src/compiler/generate.ml
src/compiler/pluginSchema.ml
src/examples/1/dune
src/examples/2/dune
src/runtime/builderInc.ml
src/runtime/builderOps.ml
src/runtime/codecs.ml
src/runtime/dune
src/runtime/farPointer.ml
src/runtime/fragmentBuffer.ml
src/runtime/listPointer.ml
src/runtime/listStorageType.ml
src/runtime/messageSig.ml
src/runtime/readerInc.ml
src/runtime/structPointer.ml
src/tests/dune
src/unix/dune
src/unix/iO.ml

- Comments need to go after the fields, not before.
- Removed some inlining attributes; even flambda (with OCaml 5.0.0) complains about these now!
- Fixed dependency on ounit2 (lower-bounds check was failing).

Fix invalid doc-comments and inline attributes

---

src/benchmark/dune
src/compiler/dune
src/compiler/generate.ml
src/examples/1/dune
src/examples/2/dune
src/runtime/dune
src/runtime/message.ml
src/tests/dune
src/unix/dune

These cause confusing compiler warnings for users, which can't be disabled automatically, and the inlining isn't being used anyway since https://github.com/capnproto/capnp-ocaml/pull/83.

Remove all `inlined` attributes
